//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALCops.ApplicationCop {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationCopAnalyzers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationCopAnalyzers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ALCops.ApplicationCop.ApplicationCopAnalyzers", typeof(ApplicationCopAnalyzers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lowFields are calculated fields and should not allow direct user input. By default, the Editable property must be set to false. If the property is missing or set to true, this diagnostic is raised. In rare cases where a FlowField needs to be editable, you should explicitly set Editable = true and document the reason with a comment. Alternatively, use pragma directives (#pragma warning disable/restore) to suppress the diagnostic, always with a justification for the deviation..
        /// </summary>
        internal static string FlowFieldsShouldNotBeEditableDescription {
            get {
                return ResourceManager.GetString("FlowFieldsShouldNotBeEditableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlowFields must have the Editable property set to false. If you require it to be true, set it explicitly and add a comment justifying the exception..
        /// </summary>
        internal static string FlowFieldsShouldNotBeEditableFormat {
            get {
                return ResourceManager.GetString("FlowFieldsShouldNotBeEditableFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlowFields should not be editable.
        /// </summary>
        internal static string FlowFieldsShouldNotBeEditableTitle {
            get {
                return ResourceManager.GetString("FlowFieldsShouldNotBeEditableTitle", resourceCulture);
            }
        }
    }
}
